"""Versioned financial facts; explicit knowledge time, provenance and coverage.

These contracts validate supplied evidence, not completeness of market history.
No provider is contacted implicitly and missing facts are never guessed.
"""

from .dividend_migration_v2 import (
    DIVIDEND_LIFECYCLE_MIGRATION_SCHEMA_ID_V2,
    DividendLifecycleMigrationReceiptV2,
    DividendLifecycleMigrationV2,
    LegacyTimingBindingV2,
    LegacyV1BindingV2,
    migrate_dividend_lifecycle_v1_to_v2,
)
from .dividends import (
    DIVIDEND_LIFECYCLE_SCHEMA_ID,
    UNSUPPORTED_DIVIDEND_FEATURES,
    CashDeduction,
    CurrencyReference,
    DividendEntitlement,
    DividendLifecycle,
    DividendPayment,
    DividendPaymentElection,
    DividendProposal,
    EvidenceTiming,
    IssuerFxConversion,
    PaymentPolicy,
    PhaseEvidence,
    PublishedAmount,
    RoundingPolicy,
)
from .dividends_v2 import (
    DIVIDEND_LIFECYCLE_SCHEMA_ID_V2,
    DividendEntitlementV2,
    DividendLifecycleV2,
    DividendPaymentElectionV2,
    DividendPaymentV2,
    DividendProposalV2,
    IssuerFixingTimeV2,
    IssuerFxConversionV2,
    PaymentPolicyV2,
    PhaseEvidenceV2,
)
from .fx import PIT_FX_SCHEMA_ID, FxAsOf, PitFxRate, fx_rate_asof, select_pit_fx
from .publication_time_v2 import (
    EVIDENCE_TIMING_SCHEMA_ID_V2,
    AdmissionBoundaryV2,
    AvailabilityDecisionV2,
    DowngradeReasonV2,
    EvidenceRevisionV2,
    EvidenceTimingBuildResultV2,
    EvidenceTimingV2,
    NominalPublicationIntervalV2,
    PhysicalClockAccuracyV2,
    PublicationDisplayRuleV2,
    PublicationZoneEvidenceV2,
    SourceMaterialReferenceV2,
    SourcePublicationV2,
    build_evidence_timing_v2,
)

SCHEMA_VERSION = "puresaber.financial-foundations/1"

__all__ = [
    "DIVIDEND_LIFECYCLE_MIGRATION_SCHEMA_ID_V2",
    "DIVIDEND_LIFECYCLE_SCHEMA_ID",
    "DIVIDEND_LIFECYCLE_SCHEMA_ID_V2",
    "EVIDENCE_TIMING_SCHEMA_ID_V2",
    "PIT_FX_SCHEMA_ID",
    "SCHEMA_VERSION",
    "UNSUPPORTED_DIVIDEND_FEATURES",
    "AdmissionBoundaryV2",
    "AvailabilityDecisionV2",
    "CashDeduction",
    "CurrencyReference",
    "DividendEntitlement",
    "DividendEntitlementV2",
    "DividendLifecycle",
    "DividendLifecycleMigrationReceiptV2",
    "DividendLifecycleMigrationV2",
    "DividendLifecycleV2",
    "DividendPayment",
    "DividendPaymentElection",
    "DividendPaymentElectionV2",
    "DividendPaymentV2",
    "DividendProposal",
    "DividendProposalV2",
    "DowngradeReasonV2",
    "EvidenceRevisionV2",
    "EvidenceTiming",
    "EvidenceTimingBuildResultV2",
    "EvidenceTimingV2",
    "FxAsOf",
    "IssuerFixingTimeV2",
    "IssuerFxConversion",
    "IssuerFxConversionV2",
    "LegacyTimingBindingV2",
    "LegacyV1BindingV2",
    "NominalPublicationIntervalV2",
    "PaymentPolicy",
    "PaymentPolicyV2",
    "PhaseEvidence",
    "PhaseEvidenceV2",
    "PhysicalClockAccuracyV2",
    "PitFxRate",
    "PublicationDisplayRuleV2",
    "PublicationZoneEvidenceV2",
    "PublishedAmount",
    "RoundingPolicy",
    "SourceMaterialReferenceV2",
    "SourcePublicationV2",
    "build_evidence_timing_v2",
    "fx_rate_asof",
    "migrate_dividend_lifecycle_v1_to_v2",
    "select_pit_fx",
]
