"""Shared quant data utilities: Parquet cache, calendar, validation, AKShare providers."""

from quant_data_kit._version import __version__
from quant_data_kit.adapters_v2 import (
    AdapterContext,
    AdapterInstrument,
    BinanceFixtureAdapter,
    CNNeutralFixtureAdapter,
    OKXFixtureAdapter,
    ProviderAdapter,
    adapt_fixture_messages,
)
from quant_data_kit.calendar import trading_days_between
from quant_data_kit.curated import (
    CuratedSnapshot,
    Curator,
    build_session_bars,
    curate_trade_bars_from_snapshot,
    load_curated_snapshot,
)
from quant_data_kit.data_lake import (
    ArchiveReceipt,
    CapacityDecision,
    CollectionStoppedError,
    DuckDBCatalog,
    NormalizationResult,
    NormalizedSnapshot,
    RawObjectManifest,
    RawObjectReference,
    StoragePolicy,
    cleanup_archived_raw_object,
    evaluate_capacity,
    load_normalized_snapshot,
    load_raw_object,
    read_normalized_events,
    require_collection_capacity,
    validate_raw_reference,
    write_normalized_batches,
    write_normalized_events,
    write_raw_bytes,
)
from quant_data_kit.domain_v2 import (
    AssetClass,
    InstrumentSpec,
    MarginMode,
    SessionPhase,
    SymbolMapping,
    TradingSession,
    dataclass_payload,
)
from quant_data_kit.fixed_point import FixedPoint
from quant_data_kit.l2_replay import (
    BookCheckpoint,
    L2BookReconstructor,
    L2ReplayError,
    L2ReplayResult,
    replay_l2,
)
from quant_data_kit.market_clock_v2 import MarketClock
from quant_data_kit.market_events_v2 import (
    AggressorSide,
    BarEvent,
    BookAction,
    BookDeltaEvent,
    BookLevel,
    BookSide,
    BookSnapshotEvent,
    CorporateActionEvent,
    FundingRateEvent,
    MarketEvent,
    MarkPriceEvent,
    QuoteEvent,
    StatusEvent,
    TradeEvent,
    market_event_payload,
)
from quant_data_kit.panel import (
    add_industry_relative_strength,
    merge_earnings_to_panel,
    merge_northbound_to_panel,
)
from quant_data_kit.schemas_v2 import (
    SCHEMA_VERSION_V2,
    get_arrow_schema,
    get_json_schema,
    validate_arrow_table,
    validate_event_stream,
    validate_json_record,
)
from quant_data_kit.snapshots import DatasetSnapshot, create_snapshot, load_snapshot
from quant_data_kit.storage import (
    DataManifest,
    cache_covers_range,
    incremental_start_date,
    load_manifest,
    load_parquet,
    parse_date,
    save_manifest,
    save_parquet,
    should_refresh_cache,
    write_manifest,
)
from quant_data_kit.temporal import TemporalAudit, audit_point_in_time, point_in_time_join
from quant_data_kit.temporal_v2 import (
    BitemporalAudit,
    ensure_utc_datetime,
    point_in_time_join_bitemporal,
    validate_bitemporal_frame,
)
from quant_data_kit.validate import validate_price_frame

__all__ = [
    "SCHEMA_VERSION_V2",
    "AdapterContext",
    "AdapterInstrument",
    "AggressorSide",
    "ArchiveReceipt",
    "AssetClass",
    "BarEvent",
    "BinanceFixtureAdapter",
    "BitemporalAudit",
    "BookAction",
    "BookCheckpoint",
    "BookDeltaEvent",
    "BookLevel",
    "BookSide",
    "BookSnapshotEvent",
    "CNNeutralFixtureAdapter",
    "CapacityDecision",
    "CollectionStoppedError",
    "CorporateActionEvent",
    "CuratedSnapshot",
    "Curator",
    "DataManifest",
    "DatasetSnapshot",
    "DuckDBCatalog",
    "FixedPoint",
    "FundingRateEvent",
    "InstrumentSpec",
    "L2BookReconstructor",
    "L2ReplayError",
    "L2ReplayResult",
    "MarginMode",
    "MarkPriceEvent",
    "MarketClock",
    "MarketEvent",
    "NormalizationResult",
    "NormalizedSnapshot",
    "OKXFixtureAdapter",
    "ProviderAdapter",
    "QuoteEvent",
    "RawObjectManifest",
    "RawObjectReference",
    "SessionPhase",
    "StatusEvent",
    "StoragePolicy",
    "SymbolMapping",
    "TemporalAudit",
    "TradeEvent",
    "TradingSession",
    "__version__",
    "adapt_fixture_messages",
    "add_industry_relative_strength",
    "audit_point_in_time",
    "build_session_bars",
    "cache_covers_range",
    "cleanup_archived_raw_object",
    "create_snapshot",
    "curate_trade_bars_from_snapshot",
    "dataclass_payload",
    "ensure_utc_datetime",
    "evaluate_capacity",
    "get_arrow_schema",
    "get_json_schema",
    "incremental_start_date",
    "load_curated_snapshot",
    "load_manifest",
    "load_normalized_snapshot",
    "load_parquet",
    "load_raw_object",
    "load_snapshot",
    "market_event_payload",
    "merge_earnings_to_panel",
    "merge_northbound_to_panel",
    "parse_date",
    "point_in_time_join",
    "point_in_time_join_bitemporal",
    "read_normalized_events",
    "replay_l2",
    "require_collection_capacity",
    "save_manifest",
    "save_parquet",
    "should_refresh_cache",
    "trading_days_between",
    "validate_arrow_table",
    "validate_bitemporal_frame",
    "validate_event_stream",
    "validate_json_record",
    "validate_price_frame",
    "validate_raw_reference",
    "write_manifest",
    "write_normalized_batches",
    "write_normalized_events",
    "write_raw_bytes",
]
